name: Bandit Security Scan

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/bandit-scan.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  bandit:
    name: Run Bandit scan
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        run: bandit -r . -f json -o bandit-report.json

      - name: Upload Bandit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bandit-security-report
          path: app/bandit-report.json
