name: ESLint Code Scan

on:
  push:
    branches:
      - main
    paths:
      - 'app/**'
      - '.github/workflows/eslint-scan.yml'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./app   # Run commands from app folder

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run ESLint scan
        run: npx eslint . --max-warnings=0

      - name: Upload ESLint report (optional)
        if: always()
        run: npx eslint . -f json -o eslint-report.json

      - name: Save report as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: app/eslint-report.json
